### PR TITLE
adds a new setting that will allow user to specify source of user loc…

### PR DESCRIPTION
**Pull request by ksobon**
### READY

This adds a new settings option that will allow users to specify how to extract user location/office when .NET version of the plugin publishes info about plugins. Currently the method uses a hard coded setup where MachineName is extracted from user PC. This works under assumption that HOK machine names are following the pattern of XXX-YY-ZZZ where: 

- XXX is type of machine ex. LPT, DSK, etc. 
- YY is the office code ex. NY, CHI etc.
- ZZZ is the machine number ex. 100

With this settings we will allow user to still use the MachineName but instead of assuming that their naming convention matches that of HOK, we will allow them to specify a Regex pattern + group to extract the office location from. 

image

This example will parse the above string into two groups: 

- "-YY-"
- YY

By allowing user to select which group their want we can extract the computer name. Also, this method and schema will allow future expansion to get the location from other sources.

### CODE REVIEW

**Comment by ksobon** [comment]
@djsiroky totally agree. I was going to do exactly that and provide more info/examples for each option. I didn't want to start documentation/help files until we have a solution that works and was properly tested. I would hate to document now, just to realize that we need to use a different method and redo the documentation again. So once I have a chance to test these at HOK, I will document all of the changes.

**Comment by djsiroky** [comment]
@ksobon Sounds good. There's definitely some enhancements that could be beneficial (i.e. RegEx syntax checking, bolding/highlighting the selected group in the RegEx pattern) but could come later with the documentation

**Comment by ksobon** [comment]
@djsiroky I wouldn't want to treat MC as a place to develop Regex patterns. There are pretty good online resources for doing that ex: https://regex101.com/. I will post a link to it in a help dialog when we get around to that, but I wasn't thinking about highlighting these to users in MC in any fashion.

**Comment by djsiroky** [comment]
@ksobon  I was thinking just error-checking to prevent invalid RegEx's from being passed, even if by mistake. It could be something as like (pseudo-code): 
```javascript
try { 
    new RegExp(usersInvalidRegex);
    addToRegexList();
} catch(err) { 
    displayError(err);
}
```
on try to add it as a pattern. May save us from having to error-handle invalid inputs further down the line or troubleshoot at a time that is well after the invalid regex is set. Just something to consider.

**Comment by ksobon** [comment]
I don't think that would actually "validate" the `Regex` since its constructor accepts a `string` as an input. The error for patterns that fail to evaluate would crop up on .NET side when we actually try and apply such regex to a string to find a match. I am not sure we can safeguard against that on JS side. Something like this would work on .NET side though: 

image

**Comment by djsiroky** [comment]
It does try to 'compile' the RegExp, even when given a string as the constructor and returns a relevant error when given an invalid expression:

image

image

**Pull request closed without merging**
