### PR TITLE
Feature/recognize citrix machines

### PR DESCRIPTION
**Pull request by ksobon**
### READY

This adds new settings for recognizing Citrix machines. Currently we use a Machine Name based check knowing that Citrix machines end with "svr". This can be replaced with a Regex based check where user can pick the method. I can see at least one more type of check that we can do in the future, and that would be checking if user has a Citrix client installed. 

Once we verify that user is indeed on a Citric machine, they don't have a local temp folder on a C drive like most other machines. C access is restricted on Citrix machines, so we need input from user with a temp folder location. Family Publishing tool uses that to temporarily export the families there to get proper file size etc. 

image

### CODE REVIEW

**Comment by djsiroky** [comment]
This may be expanding the scope of work for this particular PR, but I was just thinking about abstraction on this one a bit... Should we treat it like a switch statement to handle different cases, then falling back to the default? Not in implementation per se, but in how the user sets it up.

For example, I suppose people may want to use different temp locations based on machine name, Revit year, etc.

I guess this check would actually be on the C# side, but you'd have to deal with ordering the test cases and then that'd determine the order that you'd test them in, finally falling back to some default location.
```js
function testCases(machineName, cases) {
	cases.forEach((case) => {
		if (case.pattern.test(machineName)) return case.location;
	})
	return defaultTempLocation;
}

const tempLocation = testCases('KC-L3032', cases);
```

```html
<fieldset ng-repeat="for case in case">
	<label>{{case.name}} Identifier Source</label>
	<input>...</input>
	<label>{{case.name}} Pattern</label>
	<input>...</input>
	<label>{{case.name}} Temp Path</label>
	<input>...</input>
</fieldset>
```

image

**Comment by ksobon** [comment]
I don't think that users would have a different temp drive location based on "office location". I mean its possible, but unlikely because IT would want to prevent that from happening. In a corporation you want to make sure that every user is mapped to the same letter drives, or you might be asking yourself for trouble. Normally they are. 

In this particular case we are dealing with VM machines like Citrix where they are just virtual clients and to allow external users onto that machine, they are setup to limit access to Explorer. The idea is that people can use Revit from home, but they don't have access to the folder structure etc. These Citrix machines don't have a C drive that we can access, so we are asking in the Settings to give us a different location. In this case its B. 

I don't think we need to be super flexible here just yet. Let's see how this plays out first.

**Comment by djsiroky** [comment]
Sounds good, I'm fine with keeping it as is but wanted to get an idea for something more generic down in case someone comes along with some alternative use case. But since this is just for a temp directory location, it's a major decision for most.

Just tested things out on my machine and this works great. Aproved 👍

**Comment by ksobon** [comment]
@djsiroky I really like these ideas, but I am also wary of "future-proofing" the app too much right now. That's why I am mostly saying: "Hey, let's wait and see what works, and then we will make the necessary changes". Basically in the future if we do need to make this more flexible we will have less code to change, but if we don't then we won't have any excess already in there. I am trying to keep it lean. Only put in what we need now.

**Pull request closed without merging**
